version: "3.8"
services:
  mosquitto:
    image: eclipse-mosquitto
    networks:
      - test-net
    ports:
      - target: 8883
        published: 8883
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./binds/mosquitto/config
        target: /mosquitto/config
        read_only: true
      - type: bind
        source: ./binds/mosquitto/data
        target: /mosquitto/data
      - type: bind
        source: ./binds/mosquitto/log
        target: /mosquitto/log
  server:
    build: server/.
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: udp
        mode: host
    environment:
      - REST_PORT=8080
      - SERVERADDRESS=tcp://mosquitto:1883
    networks:
      - test-net
    depends_on:
      - mosquitto
    volumes:
      - type: bind
        source: ./binds/server
        target: /binds
        read_only: true
  pub:
    build: publisher/.
    networks:
      - test-net
    depends_on:
      - mosquitto
networks:
  test-net:
    external: false
