# Compile stage
FROM golang:bullseye AS build-env
ENV CGO_ENABLED 1

ADD . /pub_src
WORKDIR /pub_src
RUN go build -gcflags "all=-N -l" -o /pub

# Final stage
FROM debian:bullseye-slim

COPY --from=build-env /pub /

# Run
CMD ["/pub"]
