name: Test

on:
  push:
    branches: [ "main" ]
    paths:
      - "server/**.go"
      - "server/go.mod"
      - "server/go.sum"
      - ".github/workflows/test.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "server/**.go"
      - "server/go.mod"
      - "server/go.sum"
      - ".github/workflows/test.yml"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'

    - name: Build
      run: |
        cd server
        go build -v ./...
        cd ..

    - name: Test
      run: |
        cd server
        go test -v ./...
        cd ..
